### ISSUE TITLE
Add threading and paging command line option

### ISSUE THREAD

**Issue by jesuiscamille** [ostrolucky/Bulk-Bing-Image-downloader#21]
Now, to change the paging and number of threads of bbid, the user needs to look into the source code and find the values at the top to modify them.

It would be nice if options such as `--threads=666` and `--paging=300` could be passed to the program :).

Anyway, bbid is awesome, and is helping me a lot in my current project. Thanks :)

**Comment by ostrolucky** [comment]
First of all, thank you for your kind words. I'm really happy it helps you :)

Regarding the proposal, I'm afraid I don't intend to expose these options on this level. I've made this easily configurable by putting it at the top of the script. Having an CLI option for it is another level though. I minimize configuration options in my projects, because I believe lot of options make for convoluted configuration and harder to use program.

Specifically, paging is something which should really be left alone. It reflects paging used by bing in backend and changing it would result in skipped images. Only time this should be touched is when bing changes paging on their side and in such case it should be changed directly in this repository, so users don't need to change it by themselves. So far though, I did not receive any reports of needing to change this. 

More easily configurable number of threads is more useful, but I believe I use sensible default. Ideally though I would like to make it scale automagically according to current throughput, so having the need to change it is eliminated altogether.

**Comment by jesuiscamille** [comment]
I thought I've responded !

The default threading parameter is causing image download fails ( The max download rate I can get is 300KB/s ).

To get TX and RX speeds in python: https://github.com/fopina/pyspeedtest

Good continuation !

**Comment by ostrolucky** [comment]
Ok, that makes sense. Default settings probably don't work too well for such slow connections. I will reopen this and evaluate how hard it would be to implement autoscaling. If it takes too much effort, I will probably go with new CLI option indeed
